# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    concat:
      repo: "puppetlabs/concat"
      ref:  "4.2.1"
    firewalld: 
      repo: "crayfishx/firewalld"
      ref:  "3.4.0"
    haproxy:
      repo: "puppetlabs/haproxy"
      ref:  "2.1.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref:  "2.1.0"
    puppet_agent:
      repo: "puppetlabs/puppet_agent"
      ref:  "1.6.0"
    selinux:
      repo: "puppet/selinux"
      ref:  "1.5.2"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.25.1"
  repositories:
    yum:
      repo: "https://github.com/bchristianv/puppet_mod-yum.git"
      ref:  "0.5.2"
