# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref:  "1.0.4"
    concat:
      repo: "puppetlabs/concat"
      ref:  "6.0.0"
    firewalld:
      repo: "crayfishx/firewalld"
      ref:  "3.4.0"
    git:
      repo: "puppetlabs/git"
      ref:  "0.5.0"
    haproxy:
      repo: "puppetlabs/haproxy"
      ref:  "4.0.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref:  "3.0.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref:  "6.1.0"
#    puppet_agent:
#      repo: "puppetlabs/puppet_agent"
#      ref:  "2.1.2"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref:  "7.3.0"
    puppetserver:
      repo: "puppet/puppetserver"
      ref:  "3.0.1"
    puppetserver_gem:
      repo: "puppetlabs/puppetserver_gem"
      ref:  "1.1.1"
    r10k:
      repo: "puppet/r10k"
      ref:  "7.0.0"
    selinux:
      repo: "puppet/selinux"
      ref:  "3.0.0"
    sshkey:
      repo: "puppetlabs/sshkeys_core"
      ref:  "1.0.2"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "6.0.0"
    yumrepo:
      repo: "puppetlabs/yumrepo_core"
      ref:  "1.0.3"
  repositories:
    yum:
      repo: "https://github.com/bchristianv/puppet_mod-yum.git"
      ref:  "1.0.1"
